name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "*/5 * * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "limpbizkitstillsuck1@gmail.com"
          git config --local user.name "mertadarma"
          git add -A
          
          arr[0]="ahh"
          arr[1]="ahh"
          arr[2]="ahhh"
          arr[3]="1"
          arr[4]="2"
          arr[5]="rifka the best girl in the world"
          arr[6]="coba tebak"
          arr[7]="ahahahahah"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
